<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<style type="text/css">
html,body {
  font-family: Helvetica, Verdana, Arial, sans-serif;
  margin: 0;
  padding: 0;
}

#top-bar {
  position: fixed;
  top: 0;
  left: 0;
  z-index: 999;
  width: 100%;
  height: 23px;
}

* html #top-bar {
  position: absolute;
}

#topbar-inner {
  height: 23px;
  background: #dddddd;
}

* html #topbar-inner {
  margin-right: 17px;
}

* html body {
  padding-top: 23px;
}

* html,* html body {
  overflow-y: hidden;
  height: 100%;
  margin-top: -23px;
}

#mainouter {
  position: relative;
  z-index: 2;
  padding-top: 25px;
  padding-bottom: 40px;
}


table
{
	font-family: "Lucida Sans Unicode", "Lucida Grande", Sans-Serif;
	font-size: 12px;
	margin: 45px;
	width: 480px;
	text-align: left;
	border-collapse: collapse;
	border: 1px solid #69c;
}
table th
{
	padding: 12px 17px 12px 17px;
	font-weight: normal;
	font-size: 14px;
	color: #039;
	border-bottom: 1px dashed #69c;
}
table td
{
	padding: 7px 17px 7px 17px;
	color: #669;
}
table tbody tr:hover td
{
	color: #339;
	background: #d0dafd;
}


A:link {text-decoration: none; color: #039;}
A:visited {text-decoration: none; color: #039;}
A:active {text-decoration: none; color: #039;}
A:hover {text-decoration: underline; color: red;}

</style>
</head>
<body>
<div id="top-bar"> 
  <div id="topbar-inner">WizardPHP Framework </div>
</div>
<div id="mainouter">
HHAHAHAHA