# MODES: development(Automatically creates tables), production
mode : development
debug : off
# DEFAULT LANGUAGE
language : en
# DATABASE
class : mysql
host  : localhost
user  : root
password : root
database : wizard
# UPDATE/INSTALL REPOSITORY
ftp_serv : ftp.wizardphp.org
ftp_user : anonymous
ftp_pass : wzd@wizardphp.org
filesdb : config/filesdb.yml
cache : wizard/cache/
