# MODES: development(Automatically creates tables), production
mode : development
debug : off
# DEFAULT LANGUAGE
language : en
# DATABASE CONFIG
class : mysql
host  : localhost
user  : user
password : password
database : database
# USER MANAGER: Verification mail
from  : wizard@wizardphp.com
title : 'Email Verification'
message: 'Verify your email address:'
