<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<style type="text/css">
html,body {
  margin: 0;
  padding: 0;
}

#top-bar {
  position: fixed;
  top: 0;
  left: 0;
  z-index: 999;
  width: 100%;
  height: 23px;
}

* html #top-bar {
  position: absolute;
}

#topbar-inner {
  height: 23px;
  background: #bbb;
}

* html #topbar-inner {
  margin-right: 17px;
}

* html body {
  padding-top: 23px;
}

* html,* html body {
  overflow-y: hidden;
  height: 100%;
  margin-top: -23px;
}

#mainouter {
  position: relative;
  z-index: 2;
  padding-top: 25px;
  padding-bottom: 40px;
}

</style>
</head>
<body>
<div id="top-bar"> 
  <div id="topbar-inner">WizardPHP Framework </div>
</div>
<div id="mainouter">