<html>
	<head>
		<title>TESTING</title>
	</head>
	<body>
		<p>
			<b>LOGIN MANAGER:</b>
			<? users_form(); ?>
		</p>
		<p>
			<b>NEW USER:</b>
				<? users_form('new'); ?>
		</p>
		<p>
			<b>TESTING LEVELS:</b>
			<? 
			if (user()) {
				print "Your level is <b>".user()."</b><br>";
				print "Your mail is ".user('mail');
			} else {
				print "Please login.";
			}
			?>
		</p><p>
		<b>LIST USERS:</b>
		<?
		edit_list('users');
		?>
		</p>
	</body>
</html>
